#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

output_file="config/public-api-nonfacade-baseline.txt"
mkdir -p "$(dirname "$output_file")"

{
    echo "# Generated by scripts/update-public-api-facade-boundary-baseline.sh"
    echo "# Public/open declarations outside Sources/SwiftFulcrum/PublicAPI"
    rg -n --no-heading \
        --glob '*.swift' \
        --glob '!Sources/SwiftFulcrum/PublicAPI/**' \
        -e '^[[:space:]]*(public|open)[[:space:]]+extension\b' \
        -e '^[[:space:]]*(public|open)[[:space:]]+(actor|class|struct|enum|protocol|typealias|var|let|func|subscript|init)\b' \
        Sources/SwiftFulcrum \
    | LC_ALL=C sort -u
} > "$output_file"

echo "Updated $output_file"
